# Generated by Django 5.2.7 on 2025-10-18 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='account_type',
            field=models.CharField(choices=[('jobseeker', 'Job Seeker'), ('employer', 'Employer'), ('admin', 'Admin')], max_length=10),
        ),
    ]
