# Generated by Django 5.2.7 on 2025-10-20 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='selected_bid',
        ),
    ]
